*Referencia  : https://communities.sas.com/t5/General-SAS-Programming/What-is-the-difference-between-strip-compress-and-trim/td-p/323286;
data _null_;
    length text $15;
    format text $char15.;
    text = '  ab   cde  f   ';
    trim = '*'||trim(text)||'*';         *Remove os espaços em braco a direita;
    compress = '*'||compress(text)||'*'; *Remove todos os espaços em braco;
    strip = '*'||strip(text)||'*';       *Remove os espaços em braco a esquerda e a direita;
    put trim;
    put compress;
    put strip;
run;
